import type { Metadata } from "next";
import { Montserrat, Mulish } from "next/font/google"
import "./globals.css";


const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-montserrat"
});

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-mulish"
});

export const metadata: Metadata = {
  title: "Happy Teeth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.variable} ${montserrat.variable}`}>
        {children}
      </body>
    </html>
  );
}
